#! /bin/sh

#export FG42_HOME=--PATH--
export FG42_HOME=$HOME/FG42

#emacs -Q --no-splash --name FG42 --title FG42 -q -l --PATH--/fg42-config.el "$@"
emacs --name FG42  -q --no-site-file --no-site-lisp --no-splash --title FG42 -l $FG42_HOME/fg42-config.el "$@"
