#! /bin/sh

#cask exec emacs -Q --no-splash --name FG42 --title FG42 -q -l /home/lxsameer/src/FG42/FG42/fg42-config.el "$@"
emacs --name FG42 -Q -q --no-splash --title FG42 -l /home/lxsameer/src/FG42/FG42/fg42-config.el "$@"
